#!/usr/bin/env bash
# install.sh - portable agentmux installer. Run inside WSL, or on macOS:
#
#   bash <(tr -d '\r' < /mnt/c/path/to/agentmux/install.sh)   # WSL
#   bash <(tr -d '\r' < install.sh)                           # macOS
#
# The tr strips CRs, because this file is usually authored on Windows.
#
# Assumes nothing about the username, distro, drive letter, checkout location,
# node version or operating system. Everything is discovered at run time, by
# capability rather than by asking which OS this is.

set -uo pipefail

info() { printf '  %s\n' "$*"; }
warn() { printf 'WARN: %s\n' "$*" >&2; }
die()  { printf 'error: %s\n' "$*" >&2; exit 1; }

# Where this script lives, even when invoked via process substitution (where
# $0 is /dev/fd/N and BASH_SOURCE is useless). Fall back to asking the user.
find_repo() {
  local src="${BASH_SOURCE[0]:-}" d
  if [ -n "$src" ] && [ -f "$src" ]; then
    d="$(cd "$(dirname "$src")" && pwd)"
    [ -f "$d/agentmux.sh" ] && { printf '%s' "$d"; return 0; }
  fi
  # Invoked from a pipe or fd: accept an explicit override.
  if [ -n "${AGENTMUX_REPO:-}" ] && [ -f "$AGENTMUX_REPO/agentmux.sh" ]; then
    printf '%s' "$(cd "$AGENTMUX_REPO" && pwd)"; return 0
  fi
  return 1
}

echo "agentmux installer"
echo

REPO="$(find_repo)" || die "cannot locate agentmux.sh.
Re-run with the checkout path, e.g.:
  AGENTMUX_REPO=/mnt/c/path/to/agentmux bash <(tr -d '\r' < /mnt/c/path/to/agentmux/install.sh)"
info "harness source : $REPO/agentmux.sh"

# --- prerequisites ----------------------------------------------------------

if ! command -v wslpath >/dev/null 2>&1 && [ -d /mnt/c ]; then
  warn "wslpath missing - Windows path translation (--cwd 'C:\\...') will not work"
fi
if command -v tmux >/dev/null 2>&1; then
  info "tmux           : $(tmux -V)"
else
  if command -v brew >/dev/null 2>&1; then
    die "tmux not installed. Install it first:  brew install tmux"
  fi
  die "tmux not installed. Install it first:  sudo apt update && sudo apt install -y tmux"
fi

NODE_BIN="$(ls -d "$HOME"/.nvm/versions/node/*/bin 2>/dev/null | sort -V | tail -1)"
NODE_FOUND="$(command -v node 2>/dev/null || true)"
if [ -n "$NODE_BIN" ]; then
  info "node (nvm)     : $("$NODE_BIN/node" --version 2>/dev/null)"
elif [ -n "$NODE_FOUND" ] && case "$NODE_FOUND" in /mnt/*) false ;; *) true ;; esac; then
  # No nvm, but a native node that node_bin() will fall back to (Homebrew, say).
  info "node           : $NODE_FOUND ($("$NODE_FOUND" --version 2>/dev/null), no nvm)"
elif [ -d /mnt/c ]; then
  warn "no nvm-managed node found. The harness prepends the newest nvm node bin to
       each pane's PATH so agent CLIs resolve to Linux binaries instead of the
       Windows npm shims. Without it, 'codex' may resolve to a Windows shim that
       cannot run under Linux. Install node via nvm before spawning codex."
else
  warn "no node found. Install one (e.g. 'brew install node') before spawning codex."
fi

# --- launcher ---------------------------------------------------------------

BIN="$HOME/.local/bin"
mkdir -p "$BIN"
cat > "$BIN/agentmux" <<LAUNCHER
#!/usr/bin/env bash
# Generated by agentmux install.sh on $(date -Iseconds).
# Strips CRs from the Windows-authored source at run time, so editing the .sh
# from Windows cannot break it. Do not invoke the .sh directly.
# AGENTMUX_REPO lets agentmux.sh find sibling tooling (taskmgmt/task.py). The
# harness cannot derive its own location: it runs via process substitution, so
# \$0 is /dev/fd/N and BASH_SOURCE is useless.
export AGENTMUX_REPO="$REPO"
exec bash <(tr -d "\r" < "$REPO/agentmux.sh") "\$@"
LAUNCHER
chmod +x "$BIN/agentmux"
info "launcher       : $BIN/agentmux"

case ":$PATH:" in
  *":$BIN:"*) ;;
  *) warn "$BIN is not on your PATH. Add to ~/.bashrc:
         export PATH=\"\$HOME/.local/bin:\$PATH\"" ;;
esac

# --- agent CLIs -------------------------------------------------------------

echo
if [ -d /mnt/c ]; then
  echo "agent CLIs (must be Linux builds - Windows npm shims fail under WSL):"
else
  echo "agent CLIs:"
fi
PATH="${NODE_BIN:-}:$PATH"
for cli in codex claude; do
  p="$(command -v "$cli" 2>/dev/null)"
  if [ -z "$p" ]; then
    info "$cli : MISSING   -> npm install -g $( [ "$cli" = codex ] && echo '@openai/codex@latest' || echo '@anthropic-ai/claude-code' )"
  elif case "$p" in /mnt/*) true ;; *) false ;; esac; then
    warn "$cli resolves to a WINDOWS path ($p) - it will crash inside WSL.
       Install the Linux build: npm install -g $( [ "$cli" = codex ] && echo '@openai/codex@latest' || echo '@anthropic-ai/claude-code' )"
  else
    info "$cli : $p"
  fi
done

# --- Windows entry point ----------------------------------------------------

if command -v wslpath >/dev/null 2>&1; then
  WINREPO="$(wslpath -w "$REPO" 2>/dev/null)"
  if [ -n "$WINREPO" ]; then
    echo
    echo "Optional - drive it from Windows by adding this to your user PATH:"
    info "$WINREPO"
    info "(then 'agentmux list' works from cmd/PowerShell via agentmux.cmd)"
    info "NOTE: the .cmd entry point discards exit codes and puts arguments on a"
    info "      cmd.exe pipeline. Prefer driving the harness from WSL directly."
  fi
fi

cat <<'NEXT'

Next steps
  1. Share credentials/config with the Windows installs (optional):
       ./link-windows-state.sh --check
       ./link-windows-state.sh --apply
  2. Log in to each agent CLI inside WSL (interactive, one time):
       codex login
       claude          # then /login
  3. First run of a TUI agent shows setup modals. Answer them by hand before
     using `ask`, or the harness will type your prompt into a menu:
       agentmux spawn rev --cli claude --cwd .
       tmux -L agentmux attach -t rev      # answer modals, then Ctrl-b d
  4. Read ANALYSIS_2026-09-18.md before trusting any answer this tool relays.
NEXT
